version: '3.8'

services:
  # PHP + Apache service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: toroller
      DB_USERNAME: toroller_user
      DB_PASSWORD: toroller_password

  # MySQL service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: toroller
      MYSQL_USER: toroller_user
      MYSQL_PASSWORD: toroller_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db

volumes:
  mysql_data:
